services:
  - type: web
    name: fastapi-tesseract
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y tesseract-ocr libtesseract-dev
      pip install -r requirements.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app
